#!/bin/bash
# get the values of WATER and STIR from environment variables
WATER=${WATER:-2}
STIR=${STIR:-1}
# add the values together
SUM=$((WATER + STIR))
# output the result
echo "The sum of WATER and STIR is: $SUM"
